# Generated by Django 3.1.4 on 2021-01-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=36)),
                ('description', models.TextField(max_length=50)),
                ('pic1', models.ImageField(upload_to='files/images')),
                ('pic2', models.ImageField(upload_to='files/images')),
                ('pic3', models.ImageField(upload_to='files/images')),
                ('pic4', models.ImageField(upload_to='files/images')),
                ('pic5', models.ImageField(upload_to='files/images')),
                ('pic6', models.ImageField(upload_to='files/images')),
                ('pic7', models.ImageField(upload_to='files/images')),
                ('pic8', models.ImageField(upload_to='files/images')),
            ],
        ),
    ]
