# Generated by Django 3.1.4 on 2021-01-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circulars',
            old_name='pdf',
            new_name='PDF',
        ),
        migrations.AddField(
            model_name='circulars',
            name='Btech',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='circulars',
            name='Mtech',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='circulars',
            name='PHD',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='circulars',
            name='everyone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='circulars',
            name='faculty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='circulars',
            name='general',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='circulars',
            name='student',
            field=models.BooleanField(default=False),
        ),
    ]
