# Generated by Django 3.1.4 on 2021-01-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulars', '0002_auto_20210123_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circulars',
            name='PDF',
            field=models.FileField(default='false', upload_to='files/pdfs'),
        ),
        migrations.AlterField(
            model_name='circulars',
            name='description',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='circulars',
            name='title',
            field=models.CharField(max_length=36),
        ),
    ]
