# Generated by Django 3.1.4 on 2021-02-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('department', models.TextField(max_length=50)),
                ('pic1', models.ImageField(upload_to='files/images')),
                ('qualification', models.TextField(max_length=50)),
                ('contact', models.TextField(max_length=100)),
                ('achievments', models.TextField(max_length=100)),
            ],
        ),
    ]
